Algoritmo "semnome"
// 
//  
// Descrição   : Constantes
// Autor(a)    : Lucas Zarzur
// Data atual  : 04/03/2021
Var

// Numéricos
PII: real
POLEGADA: real

// Caracteres
NOME_DA_EMPRESA: caractere

// Lógicos
CONSIDERA_FERIADO: logico


Inicio
PII <- 3
POLEGADA <- 2.54
NOME_DA_EMPRESA <- "Maitha Tech"
CONSIDERA_FERIADO <- verdadeiro

escreval("Númericos: ", PII, POLEGADA)
escreval("Caracteres: ", NOME_DA_EMPRESA)
escreval("Lógicos: ", CONSIDERA_FERIADO)


Fimalgoritmo