Algoritmo "semnome"
// 
//  
// Descrição   : Estruturas de Decisão -
//                      Tomada/condicional de decisão simples
// Autor(a)    : Lucas Zarzur
// Data atual  : 09/03/2021
Var
salario:inteiro

Inicio
// descomentar esse -> não será imprimido nada na tela...
//salario <- 4500

// ... e comentar esse
salario <- 5000


Se (salario >= 5000) então
    Escreva ("Proposta aceita!")
FimSe

Fimalgoritmo